import os
import argparse
from dotenv import load_dotenv
load_dotenv()

# Use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

from langchain.agents import AgentType
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint
from langchain_community.utilities.sql_database import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent


def get_llm():
    model_id = 'meta-llama/Llama-3.3-70B-Instruct'
    params = {
        "max_new_tokens": 256,
        "temperature": 0.5,
    }
    llm = HuggingFaceEndpoint(
        model=model_id,
        huggingfacehub_api_token=os.getenv("HUGGINGFACE_API_KEY"),
        **params
    )

    return ChatHuggingFace(llm=llm)


def main(query: str = None):
    llm = get_llm()
    
    # Database configuration
    mysql_username = 'root'
    mysql_password = ''  # Empty for no password
    mysql_host = '127.0.0.1'
    mysql_port = 3306
    database_name = 'Chinook'

    # Build URI
    if mysql_password:
        mysql_uri = f'mysql+mysqlconnector://{mysql_username}:{mysql_password}@{mysql_host}:{mysql_port}/{database_name}'
    else:
        mysql_uri = f'mysql+mysqlconnector://{mysql_username}@{mysql_host}:{mysql_port}/{database_name}'

    print(f"Connecting to database with URI: {mysql_uri}")
    
    # Connect to database
    db = SQLDatabase.from_uri(mysql_uri)

    # Create agent
    agent_executor = create_sql_agent(
        llm=llm,
        db=db,
        verbose=True,
        handle_parsing_errors=True,
        agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION
    )
    
    # Run query
    return agent_executor.invoke(
        query
    )


if __name__ == "__main__":
    # query = "How many employees are there?"

    # Set up argument parser
    parser = argparse.ArgumentParser()
    parser.add_argument("--prompt", type=str, help="The prompt to send to the SQL agent")
    args = parser.parse_args()
    
    query = args.prompt
    response = main(query)
    print("Final Answer:\n")
    print(response["output"])
